### ISSUE TITLE
Out of bounds for running tests on LTS-12.0 

### ISSUE THREAD

**Issue by domenkozar** [hvr/lzma#14]
```
Setup: Encountered missing dependencies:
QuickCheck >=2.8 && <2.11,
tasty >=0.10 && <1.1,
tasty-quickcheck >=0.8.3.2 && <0.10
```

**Comment by hvr** [comment]
Not sure what you mean by LTS-12.0 but you can simply try to

    cabal new-test --enable-tests --allow-newer=lzma:QuickCheck,lzma:tasty,lzma:tasty-quickcheck

but be aware that then you're operating in a configuration that isn't officially supported yet. as I haven't yet had time to review the respective API changes.
