### ISSUE TITLE
Version bounds for HUnit and QuickCheck can be loosened

### ISSUE THREAD

**Issue by adnelson** [hvr/lzma#8]
The current version bounds for these two libraries are not satisfied by the set of haskell packages in nixpkgs. However, if I loosen the bounds, the tests all pass. I made this change as a [pull request on nixpkgs](https://github.com/NixOS/nixpkgs/pull/33360), but it is probably desirable to apply here as well.

**Comment by bgamari** [comment]
Allen Nelson <notifications@github.com> writes:

> The current version bounds for these two libraries are not satisfied
> by the set of haskell packages in nixpkgs. However, if I loosen the
> bounds, the tests all pass. I made this change as a [pull request on
> nixpkgs](https://github.com/NixOS/nixpkgs/pull/33360), but it is
> probably desirable to apply here as well.
>
Indeed I am also affected by this. A bounds bump would be appreciated.

**Comment by hvr** [comment]
This was addressed via #7 and which I could finally deploy as part of the GHC 8.4.1 maintenance routine to Hackage via a meta-data revision.
